Implement drag and drop controller
microsoft/vscode-extension-samples pull request #431
Opened 2021-05-28 00:16 UTC by barbaravaldez

Drag and drop implementation in sample tree view
https://user-images.githubusercontent.com/34872381/119911928-3801f880-bf0f-11eb-8505-c3fae098559b.mov

2021-05-31 14:33 UTC, alexr00 requested changes

2021-05-31 14:33 UTC, alexr00 commented on tree-view-sample/src/testView.ts
> +	public onDidChangeTreeData: vscode.Event<Node[] | undefined> = this._onDidChangeTreeData.event;
The vscode API doesn't yet support having an array in `onDidChangeTreeData`. Is a PR for that still comming?

2021-06-18 10:09 UTC, alexr00 approved these changes
@barbaravaldez I have made some changes. Please let me know if they look ok to you!

2021-06-19 01:18 UTC, barbaravaldez commented
> @barbaravaldez I have made some changes. Please let me know if they look ok to you!

Looks good to me! Thank you, @alexr00 😃

2021-06-23 13:37 UTC, merged